apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.ecr.iamRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.ecr.iamRoleArn }}
  {{- end }}
  labels:
{{ include "version-checker.labels" . | indent 4 }}
  name: {{ include "version-checker.name" . }}
