apiVersion: v2
appVersion: "v0.10.0"
version: "v0.10.0"
description: A Helm chart for version-checker
home: https://github.com/jetstack/version-checker
name: version-checker
maintainers:
  - name: davidcollom
